name: Imaginary
on: [ push ]
jobs:
  runs:
    runs-on: ubuntu-latest
    steps:
      - name: update repos
        run: sudo apt update
      - name: install cmake
        run: sudo apt install cmake
      - name: install OpenCV
        run: sudo apt install libopencv-dev
      - name: install google logging library
        run: sudo apt install -y libgoogle-glog-dev
      - name: install high level threading library tbb
        run: sudo apt install libtbb-dev

      - uses: actions/checkout@v2
      - name: configure cmake
        run: cmake -H. -Bbuild
      - name: Build src and lib files
        run: cmake --build build --target Imaginary
#     - name: Run the project
#       run: ./build/Imaginary
      - name: debug tbb error
        run: cat build/CMakeCache.txt | grep -i TBB

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: update repos
        run: sudo apt update
      - name: install cmake
        run: sudo apt install cmake
      - name: install OpenCV
        run: sudo apt install libopencv-dev
      - name: install google logging library
        run: sudo apt install -y libgoogle-glog-dev
      - name: download catch2 v2
        run: git clone -b v2.x https://github.com/catchorg/Catch2.git
      - name: setup catch2
        run: cmake -BCatch2/build -HCatch2 -DBUILD_TESTING=OFF
      - name: build and install catch2
        run: sudo cmake --build Catch2/build --target install
      - name: install high level threading library tbb
        run: sudo apt install libtbb-dev

      - uses: actions/checkout@v2
      - name: configure cmake
        run: cmake -H. -Bbuild
      - name: Build test files
        run: cmake --build build --target Test
      - name: Run the tests
        run: ./build/Test
